// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciparmblldlwzalzoisq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcGFybWJsbGRsd3phbHpvaXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTE5NjcsImV4cCI6MjA2NTk4Nzk2N30.7rO1sGElqKQmGMy9aibwfOJlHk5DRf3iy-3MNodd1ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);